app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::resource('foodprogram','FoodProgramController');

Route::group(['middleware' => ['web']], function () {
    //
});


Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'HomeController@index');
    Route::resource('usuario', 'UsuarioController');
    Route::get('/perfil', [
      'as' => 'profile', 'uses' => 'UsuarioController@perfil']);

    Route::get('/usuario/habilitar/{id}', 'UsuarioController@habilitaUsuario')->name('habilitaUsuario');
    Route::get('/perfil/{id}', 'UsuarioController@perfil')->name('perfil');

    //Carla
    Route::resource('escuela','EscuelaController');
    //Route::get('escuela/reac/{id}', 'EscuelaController@habilitaEscuela');
    Route::get('/escuela/habilitar/{id}', 'EscuelaController@habilitaEscuela')->name('habilitaEscuela');

    Route::resource('despensa','DespensaController');
    Route::get('/despensa/habilitar/{id}', 'DespensaController@habilitaDespensa')->name('habilitaDespensa');



    //Armando Productos
    Route::resource('producto', 'ProductoController');
    Route::get('producto/reac/{id}', 'ProductoController@reactivate');

    //Armando
    Route::resource('localidad', 'LocalidadController');
    Route::get('localidad/reac/{id}', 'LocalidadController@reactivate');


    //Alejandro
    Route::resource('programa','ProgramaController');
    Route::get('programa/reac/{id}', 'ProgramaController@habilitaPrograma');

    Route::resource('provedor','ProvedorController');
    Route::get('provedor/reac/{id}', 'ProvedorController@habilitaProvedor');

    Route::resource('contrato','ContratoController');
    Route::get('contrato/reac/{id}', 'ContratoController@habilitaContrato');

    //Armando, Ordenes
    Route::resource('ordenes','OrdendeComprasController');


});

resources/views/localidades/create.blade.php
@extends('layouts.master')

@section('botones')
  <!-- Inicio del botón de guardado -->
  <div class="row">
    <button id="save" class="ui circular massive right floated teal save icon submit button" onclick="envio()">
    <i class="save icon"></i>
    </button>
  </div>
  <!-- Final del botón de guardado -->
  <div style="visibility:hidden">
    <br />..
  </div>
  <!-- Inicio del botón de regresar -->
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick="$('#regresar').modal('show');">
    <i class="chevron left icon"></i>
    </button>
  </div>
  <!-- Final del botón de guardado -->
@stop

@section('titulo_seccion')
  Registrar Localidad
@stop

@section('scripts')
  <script type="text/javascript">
    // Función para verificar si el form esta validado
    function envio(){
      $('#registro_form').form('validate form');
      //Si es true, se mostrara el modal con el id "guardar"
      if($('#registro_form').form('is valid')){
        $('#guardar').modal('show');
      }
    }
  </script>

  <script type="text/javascript">
    $(document).ready(function(){
      //Inicialización de elementos de Semantic UI
      $('.ui.modal').modal();
      $('.menu .item').tab();
      $('select').dropdown();
      //Validaciones dentro de la forma con id "registro_form"
      $('#registro_form').form({
        inline: true,
        fields:{
          nombre:{
            identifier: 'nombre',
            rules:[{
              type: 'empty',
              prompt: 'Nombre necesario'
            }]
          },
          clave_carta:{
            identifier: 'clave_carta',
            rules:[{
              type: 'exactLength[6]',
              prompt: '6 carácteres'
            }]
          },
          clave_localidad:{
            identifier: 'clave_localidad',
            rules:[{
              type: 'empty',
              prompt: 'Clave de Loclidad necesaria'
            }]
          },
          latitud:{
            identifier: 'latitud',
            rules:[{
              type: 'regExp[/^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)$/]',
              prompt: 'Longitud incorrecta'
            }]
          },
          longitud:{
            identifier: 'longitud',
            rules:[{
              type   : 'regExp[/^[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$/]',
              prompt : 'Longitud incorrecta'
            }]
          },
          altitud:{
            identifier: 'altitud',
            rules:[{
              type: 'empty',
              prompt: 'Altitud necesario'
            }]
          },
          municipio_id:{
            identifier: 'municipio_id',
            rules:[{
              type: 'empty',
              prompt: 'Seleccione un Municipio'
            }]
          },
          grado_de_marginacion_id:{
            identifier: 'grado_de_marginacion_id',
            rules:[{
              type: 'empty',
              prompt: 'Seleccione un Grado de Marginación'
            }]
          }
        }
      });
    });
  </script>
@stop

@section('contenido')
  <!--Inicio del Modal de confirmacion de regresar a index-->
  <div class="ui small modal" id="regresar">
    <i class="close icon"></i>
    <div class="ui icon header">
      <i class="archive icon"></i>
      Descartar registro
    </div>
    <div class=" content">
        <p>¿Estás seguro que deseas regresar?. Se perderan todos los datos sin guardar.</p>
    </div>
    <div class="actions">
      <div class="ui negative cancel button">
        <i class="remove icon"></i>
        No
      </div>
      <div class="ui positive button" onclick=window.location.href="/localidad">
        <i class="checkmark icon"></i>
        Si
      </div>
    </div>
  </div>
  <!--Final del Modal de confirmacion de regresar a index-->

  <!--Inicio del Modal de confirmacion de envio de formulario-->
  <div class="ui modal" id="guardar">
    <i class="close icon"></i>
    <div class="ui icon header">
      <i class="archive icon"></i>
      Guardar registro nuevo
    </div>
    <div class="content">
        <p>¿Deseas guardar el registro de la localidad?</p>
    </div>
    <div class="actions">
        <div class="ui negative cancel button">
          <i class="remove icon"></i>
          No
        </div>
        <button class="ui positive submit button" type="submit" form="registro_form">
          <i class="checkmark icon"></i>
          Si
        </button>
    </div>
  </div>
  <!--Final del Modal de confirmacion de envio de formulario-->

  <!--Inicio del Contenedor de forma de registro-->
  <div class="ui grid container">
    <div class="row">
      <div class="column">
        <!--Inicio de la forma de registro-->
        <form id="registro_form" class="ui form" action="{{route('localidad.store')}}" method="POST">
          <input type="hidden" name="_token" value="{{csrf_token()}}">
          <input type="hidden" name="_method" value="POST">
          <h4 class="ui horizontal divider header">
            <i class="tag icon">
            </i>
            Datos generales
          </h4>
          <!-- Inicio de la Seccion de datos generales -->
            <!-- Inicio de la primera fila -->
            <div class="three fields">
              <!-- Input text para el campo de "Nombre" -->
              <div class="twelve wide required field">
                <label class="prompt">Nombre</label>
                <input type="text" placeholder="Ej. El Chapulín..." name="nombre">
              </div>

              <!-- Input text para el campo de "Clave de la Localidad" -->
              <div class="two wide required field">
                <label class="prompt">Clave de Localidad</label>
                <input type="text" placeholder="Ej. 76..." name="clave_localidad">
              </div>

              <!-- Input text para el campo de "Clave Carta" -->
              <div class="two wide required field">
                <label class="prompt">Clave Carta</label>
                <input type="text" placeholder="Ej. F36C98..." name="clave_carta">
              </div>
            </div>
            <!-- Final de la primera fila -->

            <!-- Inicio de la segunda fila -->
              <div class="five fields">
                <!-- Select para el campo de "Municipio" -->
                <div class="five wide required field">
                  <label class="prompt">Municipio</label>
                  <select class="ui fluid dropdown" name="municipio_id">
                    <option value=""></option>
                    @foreach($municipios as $municipio)
                    <option value="{{$municipio->id}}">{{$municipio->nombre}}</option>
                    @endforeach
                  </select>
                </div>

                <!-- Select para el campo de "Grado de Marginación" -->
                <div class="five wide required field">
                  <label class="prompt">Grado de Marginación</label>
                  <select class="ui fluid dropdown" name="grado_de_marginacion_id">
                    <option value=""></option>
                    @foreach($grados_de_marginacion as $grado_de_marginacion)
                    <option value="{{$grado_de_marginacion->id}}">{{$grado_de_marginacion->nombre}}</option>
                    @endforeach
                  </select>
                </div>

                <!-- Input text para el campo de "Latitud" -->
                <div class="two wide required field">
                  <label class="prompt">Latitud</label>
                  <input type="text" name="latitud" placeholder="Ej. 87...">
                </div>

                <!-- Input text para el campo de "Longitud" -->
                <div class="two wide required field">
                  <label class="prompt">Longitud</label>
                  <input type="text" name="longitud" placeholder="Ej. 20...">
                </div>

                <!-- Input text para el campo de "Altitud" -->
                <div class="two wide required field">
                  <label class="prompt">Altitud</label>
                  <input type="text" name="altitud" placeholder="Ej. 70...">
                </div>
              </div>
            <!-- Final de la segunda fila -->
          <!-- Final de la Seccion de datos generales -->
        </form>
        <!--Final de la forma de registro-->
      </div>
    </div>
  </div>
  <!--Final del Contenedor de forma de registro-->
@stop

resources/views/localidades/edit.blade.php
@extends('layouts.master')

@section('botones')
  <!-- Inicio de botón de guardado -->
  <div class="row">
    <button class="ui circular massive right floated teal save icon submit button" onclick="envio()" >
    <i class="save icon"></i>
    </button>
  </div>
  <!-- Final de botón de guardado -->

  <div style="visibility:hidden">
    <br />..
  </div>

  <!-- Inicio de botón de regreso -->
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick="$('#regresar').modal('show');">
    <i class="chevron left icon"></i>
    </button>
  </div>
  <!-- Final de botón de regreso -->
@stop

@section('titulo_seccion')
  {{$localidad->nombre}}
@stop

@section('scripts')
  <script type="text/javascript">
    // Función para verificar si el form esta validado
    function envio(){
      $('.ui.form').form('validate form');
      //Si es true, se mostrara el modal con el id "guardar"
      if ($('.ui.form').form('is valid')){
        $('#guardar').modal('show');
      }
    }

    //Función para inicializar el mapa de google
    function init_map(){
      var myOptions = {
      zoom:17,
      center:new google.maps.LatLng({{$localidad->latitud}},{{$localidad->longitud}}),
      mapTypeId: google.maps.MapTypeId.ROADMAP};
      map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);
      marker = new google.maps.Marker({
        map: map,position: new google.maps.LatLng({{$localidad->latitud}},{{$localidad->longitud}})});
        infowindow = new google.maps.InfoWindow({
          content:'<strong>{{$localidad->nombre}}</strong><br/> Delegación: {{$localidad->municipio->nombre}}'});
          google.maps.event.addListener(marker, 'click', function(){
            infowindow.open(map,marker);});infowindow.open(map,marker);

    }google.maps.event.addDomListener(window, 'load', init_map);
    </script>
  <script type="text/javascript">
    $( document ).ready(function(){

        //Inicialización de elementos de Semantic UI
        $('.ui.modal').modal();
        $('.ui.accordion').accordion();
        $('.menu .item').tab();
        $('select').dropdown();

        //Validaciones dentro de la forma con id "registro_form"
        $('.ui.form').form({
          inline: true,
          fields:{
            nombre:{
              identifier: 'nombre',
              rules:[{
                type: 'empty',
                prompt: 'Nombre necesario'
              }]
            },
            clave_carta:{
              identifier: 'clave_carta',
              rules:[{
                type: 'exactLength[6]',
                prompt: '6 carácteres'
              }]
            },
            clave_localidad:{
              identifier: 'clave_localidad',
              rules:[{
                type: 'empty',
                prompt: 'Clave de Loclidad necesaria'
              }]
            },
            latitud:{
              identifier: 'latitud',
              rules:[{
                type: 'regExp[/^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)$/]',
                prompt: 'Longitud incorrecta'
              }]
            },
            longitud:{
              identifier: 'longitud',
              rules:[{
                type   : 'regExp[/^[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$/]',
                prompt : 'Longitud incorrecta'
              }]
            },
            altitud:{
              identifier: 'altitud',
              rules:[{
                type: 'empty',
                prompt: 'Altitud necesario'
              }]
            },
            municipio_id:{
              identifier: 'municipio_id',
              rules:[{
                type: 'empty',
                prompt: 'Seleccione un Municipio'
              }]
            },
            grado_de_marginacion_id:{
              identifier: 'grado_de_marginacion_id',
              rules:[{
                type: 'empty',
                prompt: 'Seleccione un Grado de Marginación'
              }]
            }
          }
        });
      });
  </script>
@stop

@section('contenido')
<!--Inicio de Seccion de mensaje de informacion-->
<div class="ui teal message"><i class="info circle icon"></i>Informacion de la localidad </div>
<!--Fin de Seccion de mensaje de informacion-->

<!--Seccion de mapa-->
<div  class="row">
  <div id='gmap_canvas' style='height:300px;width:100%;'>
  </div>
</div>
<!--Seccion de mapa-->
<br>
<!--Inicio Modal de confirmacion de regreso a show-->
<div class="ui small modal" id="regresar">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="archive icon"></i>
    Descartar registro
  </div>
  <div class=" content">
      <p>¿Estás seguro que deseas regresar?. Se perderan todos los campos.</p>
  </div>
  <div class="actions">

    <div class="ui negative cancel button">
      <i class="remove icon"></i>
      No
    </div>
    <div class="ui positive button" onclick=window.location.href="/localidad/{{$localidad->id}}">
      <i class="checkmark icon"></i>
      Si
    </div>
  </div>
</div>
<!--Final Modal de confirmacion de regreso a show-->

<!--Inicio Modal de confirmacion de envio de modificaciones-->
<div class="ui small modal" id="guardar">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="archive icon"></i>
    Guardar cambios
  </div>
  <div class="content">
      <p>¿Deseas guardar los cambios?</p>
  </div>
  <div class="actions">
      <div class="ui negative cancel button">
        <i class="remove icon"></i>
        No
      </div>
      <button class="ui positive submit button" type="submit" form="editar">
        <i class="checkmark icon"></i>
        Si
      </button>
  </div>
</div>
<!--Final Modal de confirmacion de envio de modificaciones-->

<div class="ui grid container">
  <!--Inicio Forma de carga de datos y edicion-->
  <form id="editar" class="ui form" action="{{route('localidad.update', $localidad->id)}}" method="POST" novalidate>
    <input type="hidden" name="_token" value="{{csrf_token()}}">
    <input type="hidden" name="_method" value="PATCH">
    <!--Inicio de accordion-->
    <div class="ui styled fluid accordion">
      <!--Titulo primero-->
      <div class="title active">
        <i class="dropdown icon"></i>
        Datos generales
      </div>
      <!--Titulo primero-->

      <!--Primera seccion-->
      <div  class="ui grid container content active">
        <!-- Inicio del Primer renglón -->
        <div class="row">
          <!-- Input text para el campo "Nombre de la Localidad" -->
          <div class="six wide required column">
            <label class="prompt"><strong>Nombre de la Localidad:</strong></label>
            <input type="text" placeholder="Ej. El Chapulín..." name="nombre" value="{{$localidad->nombre}}">
          </div>
        </div>
        <!-- Final del Primer renglón -->

        <!-- Inicio del Segundo renglón -->
        <div class="row">
          <!-- Input text para el campo "Clave de Localidad" -->
          <div class="three wide required column">
            <label class="prompt"><strong>Clave de Localidad:</strong></label>
            <input type="text" placeholder="Ej. 076..." name="clave_localidad" value="{{$localidad->clave_localidad}}">
          </div>
          <!-- Input text para el campo "Clave Carta" -->
          <div class="three wide required column">
            <label class="prompt"><strong>Clave Carta:</strong></label>
            <input type="text" placeholder="Ej. F36C98..." name="clave_carta" value="{{$localidad->clave_carta}}">
          </div>
        </div>
        <!-- Final del Segundo renglón -->

        <!-- Inicio del Tercer renglón -->
        <div class="row">
          <!-- Select para el campo "Municipio" -->
          <div class="three wide required column">
            <label class="prompt">Municipio:</label>
            <select class="ui fluid dropdown" name="municipio_id">
              @foreach($municipios as $municipio)
                @if($localidad->municipio_id == $municipio->id)
                  <option value="{{$municipio->id}}" selected="selected">{{$municipio->nombre}}</option>
                @else
                  <option value="{{$municipio->id}}">{{$municipio->nombre}}</option>
                @endif
              @endforeach
            </select>
          </div>

          <!-- Select para el campo "Grado de Marginación" -->
          <div class="four wide required column">
            <label class="prompt"><strong>Grado de Marginación:</strong></label>
            <select class="ui fluid dropdown" name="grado_de_marginacion_id">
              @foreach($grados_de_marginacion as $grado_de_marginacion)
                @if($localidad->grado_de_marginacion_id == $grado_de_marginacion->id)
                  <option value="{{$grado_de_marginacion->id}}">{{$grado_de_marginacion->nombre}}</option>
                @else
                  <option value="{{$grado_de_marginacion->id}}">{{$grado_de_marginacion->nombre}}</option>
                @endif
              @endforeach
            </select>
          </div>
        </div>
        <!-- Final del Tercer renglón -->

        <!-- Inicio del Cuarto renglón -->
        <div class="row">
          <!-- Input text para el campo "Latitud" -->
          <div class="two wide required column">
            <label class="prompt"><strong>Latitud:</strong></label>
            <input type="text" name="latitud" placeholder="Ej. 87..." value="{{$localidad->latitud}}">
          </div>

          <!-- Input text para el campo "Longitud" -->
          <div class="two wide required column">
            <label class="prompt"><strong>Longitud</strong></label>
            <input type="text" name="longitud" placeholder="Ej. 20..." value="{{$localidad->longitud}}">
          </div>

          <!-- Input text para el campo "Altitud" -->
          <div class="two wide required column">
            <label class="prompt"><strong>Altitud</strong></label>
            <input type="text" name="altitud" placeholder="Ej. 70..." value="{{$localidad->altitud}}">
          </div>
        </div>
        <!-- Final del Cuarto renglón -->
      </div>
      <!--Primera seccion-->
    </div>
    <!--Fin de accordion-->
  </form>
  <!--Final Forma de carga de datos y edicion-->
</div>
@stop

resources/views/localidades/show.blade.php
@extends('layouts.master')

@section('botones')
  <div class="row">
  @if($localidad->deleted_at == NULL)
    <button class="  ui circular massive right floated teal write icon submit button"  onclick=window.location.href="/localidad/{{$localidad->id}}/edit">
  @else
    <button class="  ui circular massive right floated teal write icon submit disabled button"  onclick=window.location.href="/localidad/{{$localidad->id}}/edit">
  @endif
      <i class="write icon"></i>
    </button>
  </div>

  <div style="visibility:hidden">
    <br />..
  </div>

  <div class="row">
  @if($localidad->deleted_at == NULL)
    <button class="  ui circular massive right floated teal trash outline icon button" onclick="$('#eliminar').modal('show');" >
      <i class="trash outline icon"></i>
  @else
    <button class="  ui circular massive right floated teal undo icon button" onclick="$('#habilitar').modal('show');" >
      <i class=" undo icon"></i>
  @endif
    </button>
  </div>

  <div style="visibility:hidden">
    <br />..
  </div>

  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick=window.location.href="/localidad">
      <i class="chevron left icon"></i>
    </button>
  </div>
@stop

@section('titulo_seccion')
  {{$localidad->nombre}}
@stop

@section('scripts')
  <script>
    $( document ).ready(function() {
      // Inicialización de elementos de Semantic UI
      $('.ui.accordion').accordion();
    });
  </script>

  <script>
      // Función para inicializar el mapa de google
      function init_map(){
        var myOptions = {
        zoom:17,
        center:new google.maps.LatLng({{$localidad->latitud}},{{$localidad->longitud}}),
        mapTypeId: google.maps.MapTypeId.ROADMAP};
        map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);
        marker = new google.maps.Marker({
          map: map,position: new google.maps.LatLng({{$localidad->latitud}},{{$localidad->longitud}})});
          infowindow = new google.maps.InfoWindow({
            content:'<strong>{{$localidad->nombre}}</strong><br/>Delegación {{$localidad->municipio->nombre}}'});
            google.maps.event.addListener(marker, 'click', function(){
              infowindow.open(map,marker);});infowindow.open(map,marker);
      }google.maps.event.addDomListener(window, 'load', init_map);
  </script>
@stop

@section('contenido')
  <!-- Inicio del Modal de confirmacion de regreso a index -->
  <div class="ui small modal" id="eliminar">
    <i class="close icon"></i>
    <div class="ui icon header">
      <i class="archive icon"></i>
      Eliminar Localidad
    </div>
    <div class=" content">
      <p>¿Seguro que deseas eliminar la localidad {{$localidad->nombre}}?</p>
    </div>
    <div class="actions">
        <div class="ui negative cancel button">
          <i class="remove icon"></i>
          No
        </div>
        <button class="ui positive submit button "  type="submit" form="vista" value="delete">
          <i class="checkmark icon"></i>
          Si
        </button>
    </div>
  </div>
  <!-- Final del Modal de confirmacion de regreso a index -->

  <!-- Inicio del Modal de confirmacion de habilitacion de localidad -->
  <div class="ui small modal" id="habilitar">
    <i class="close icon"></i>
    <div class="ui icon header">
      <i class="archive icon"></i>
      Reactivar Localidad
    </div>
    <div class=" content">
      <p>¿Seguro que deseas reactivar la localidad {{$localidad->nombre}}?</p>
    </div>
    <div class="actions">
        <div class="ui negative cancel button">
          <i class="remove icon"></i>
          No
        </div>
        <button class="ui positive submit button " onclick=window.location.href="/localidad/reac/{{$localidad->id}}">
          <i class="checkmark icon"></i>
          Si
        </button>
    </div>
  </div>
  <!-- Final del Modal de confirmacion de habilitacion de localidad -->

  <!--Inicio de forma de visualizacion que utiliza el metodo destroy para eliminar localidad-->
  <form id="vista" action="{{route('localidad.destroy', $localidad->id)}}" method="POST" >
    <input type="hidden" name="_token" value="{{csrf_token()}}">
    <input type="hidden" name="_method" value="DELETE">
    <!--Inicio de validacion de localidad no eliminada para seccion de informacion-->
    @if($localidad->deleted_at == NULL)
      <div class="ui message"><i class="info circle icon"></i>Informacio de la Localidad </div>
    @else
      <div class="ui negative message"><i class="info circle icon"></i>Localidad deshabilitada. Para editar deshacer eliminación. </div>
    @endif
    <!--Final de validacion de localidad no eliminada para seccion de informacion-->

    <!--Inicio de Seccion de mapa-->
    <div  class="row">
      <div id='gmap_canvas' style='height:300px;width:100%;'>
      </div>
    </div>
    <!--Fin de Seccion de mapa-->
    <br>
    <!--Inicio de accordion-->
    <div class="ui styled fluid accordion">
      <!--Titulo primero-->
      <div class="title active">
        <i class="dropdown icon"></i>
        Datos generales
      </div>
      <!--Titulo primero-->

      <!--Primera seccion-->
      <div class="content active ui container grid">
        <!-- Inicio del Primer renglón -->
        <div class="row">
          <!-- Text field para el campo "Nombre de la Localidad" -->
          <div class="ui eight wide column">
            <strong>Nombre de la Localidad:</strong> {{$localidad->nombre}}
          </div>
        </div>
        <!-- Final del Primer renglón -->

        <!-- Inicio del Segundo renglón -->
        <div class="row">
          <!-- Text field para el campo "Clave de Localidad" -->
          <div class="ui three wide column">
            <strong>Clave de Localidad:</strong> {{$localidad->clave_localidad}}
          </div>
          <!-- Text field para el campo "Nombre Carta" -->
          <div class="ui three wide column">
            <strong>Clave Carta:</strong> {{$localidad->clave_carta}}
          </div>
        </div>
        <!-- Final del Segundo renglón -->

        <!-- Inicio del Tercer renglón -->
        <div class="row">
          <!-- Text field para el campo "Municipio" -->
          <div class="ui three wide column">
            <strong>Delegación:</strong> {{$localidad->municipio->nombre}}
          </div>
          <!-- Text field para el campo "Grado de Marginación" -->
          <div class="ui four wide column">
            <strong>Grado de Marginación:</strong> {{$localidad->grado_de_marginacion->nombre}}
          </div>
        </div>
        <!-- Final del Tercer renglón -->

        <!-- Inicio del Cuarto renglón -->
        <div class="row">
          <!-- Text field para el campo "Latitud" -->
          <div class="ui two wide column">
            <strong>Latidud:</strong> {{$localidad->latitud}}
          </div>
          <!-- Text field para el campo "Longitud" -->
          <div class="ui two wide column">
            <strong>Longitud:</strong> {{$localidad->longitud}}
          </div>
          <!-- Text field para el campo "Altitud" -->
          <div class="ui two wide column">
            <strong>Altitud:</strong> {{$localidad->altitud}}
          </div>
        </div>
        <!-- Final del Cuarto renglón -->
      </div>
      <!--Primera seccion-->
    </div>
    <!--Fin de accordion-->
  </form>
  <!--Final de forma de visualizacion que utiliza el metodo destroy para eliminar Localidad-->

@stop