app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::resource('foodprogram','FoodProgramController');

Route::group(['middleware' => ['web']], function () {
    //
});


Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'HomeController@index');
    Route::resource('usuario', 'UsuarioController');
    Route::get('/perfil', [
      'as' => 'profile', 'uses' => 'UsuarioController@perfil']);

    Route::get('/usuario/habilitar/{id}', 'UsuarioController@habilitaUsuario')->name('habilitaUsuario');
    Route::get('/perfil/{id}', 'UsuarioController@perfil')->name('perfil');

    //Carla
    Route::resource('escuela','EscuelaController');
    //Route::get('escuela/reac/{id}', 'EscuelaController@habilitaEscuela');
    Route::get('/escuela/habilitar/{id}', 'EscuelaController@habilitaEscuela')->name('habilitaEscuela');

    Route::resource('despensa','DespensaController');
    Route::get('/despensa/habilitar/{id}', 'DespensaController@habilitaDespensa')->name('habilitaDespensa');



    //Armando Productos
    Route::resource('producto', 'ProductoController');
    Route::get('producto/reac/{id}', 'ProductoController@reactivate');

    //Armando
    Route::resource('localidad', 'LocalidadController');
    Route::get('localidad/reac/{id}', 'LocalidadController@reactivate');


    //Alejandro
    Route::resource('programa','ProgramaController');
    Route::get('programa/reac/{id}', 'ProgramaController@habilitaPrograma');

    Route::resource('provedor','ProvedorController');
    Route::get('provedor/reac/{id}', 'ProvedorController@habilitaProvedor');

    Route::resource('contrato','ContratoController');
    Route::get('contrato/reac/{id}', 'ContratoController@habilitaContrato');

    //Armando, Ordenes
    Route::resource('ordenes','OrdendeComprasController');


});

app/Despensa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Despensa extends Model
{
    use SoftDeletes;

    //Campos llenables en tabla
    protected $fillable = ['programa_id'];

    protected $primaryKey = 'id_despensa';
    //Varable para la utilización del SoftDelete

    protected $dates = ['deleted_at'];

    //Variable para el manejo de la tabla llamada "despensas"
    protected $table = 'despensas';

    /* Función que devuelve el model de FoodProgram relacionada con Despensa
    Función relación 1 (FoodProgram) a N (Despensa) */
    public function programa()
    {
        return $this->belongsTo('App\Programa');
    }
    public function productos()
    {
        return $this->belongsToMany('App\Producto')->withPivot('cantDiariaNino', 'diasEntrega');

    }

}

app/Http/Controllers/DespensaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Despensa;
use App\Programa;
use App\Producto;


class DespensaController extends Controller
{

    public function index(){

        $despensas = Despensa::withTrashed()->orderBy('id_despensa', 'desc')->paginate(8);
        return view('despensas.index')
                ->with('despensas', $despensas);

    }

    public function create(){

      $productos = Producto::all();
      $programas = Programa::all();
      return view('despensas.create')
              ->with('productos', $productos)
              ->with('programas', $programas); //Regresa la vista del create
    }



    public function store(Request $request){

      $despensa = new Despensa;
      $despensa->programa_id = $request->programa_id;
      $despensa->save();
      //relacion
      $productos = Producto::all();
      foreach($productos as $producto){

        $cantDiariaNino="cantDiariaNino".$producto->id;
        $diasEntrega="diasEntrega".$producto->id;
        if ($request->has($cantDiariaNino) && $request->has($diasEntrega) ) {
            $despensa->productos()->attach($producto->id, ['cantDiariaNino' => $request->$cantDiariaNino,'diasEntrega' => $request->$diasEntrega]);
        }
      }

     return view('despensas.show')->with('despensa', $despensa);
    }

    public function show($id){
      //Se obtiene la despensa deseada
      $despensa = Despensa::withTrashed()->where('id_despensa', '=', $id)->first();
      return view('despensas.show')->with('despensa', $despensa);

    }


    public function edit($id){

      $despensa = Despensa::where('id_despensa', '=', $id)->first();
      $productostodos = Producto::all();
      $programas = Programa::all();

      return view('despensas.edit')
              ->with('despensa', $despensa)
              ->with('productostodos', $productostodos)
              ->with('programas', $programas);

    }

    public function update(Request $request, $id){

      $despensa = Despensa::find($id);
      $productostodos = Producto::all();

      //tabla foreign key
      $despensa->programa_id = $request->programa_id;
      $despensa->push();
      $relacionadas=array();
      //RELACIONES
      foreach($productostodos as $productotodo){


        foreach($despensa->productos as $producto){
          $relacionadas[$producto->id]=$producto->id;
        }

          if(in_array($productotodo->id,$relacionadas)){

            $cantDiariaNino="cantDiariaNino".$productotodo->id;
            $diasEntrega="diasEntrega".$productotodo->id;
            if($request->has($cantDiariaNino) || $request->has($diasEntrega)){
              //dd($request->$cantDiariaNino);
              $pivots = array('cantDiariaNino' => $request->$cantDiariaNino ,'diasEntrega' => $request->$diasEntrega );
              $despensa->productos()->updateExistingPivot($productotodo->id,$pivots);
            }

          }
          //si no esta relacionada
          else{
            //dd("no");
            $cantDiariaNino="cantDiariaNino".$productotodo->id;
            $diasEntrega="diasEntrega".$productotodo->id;
            if($request->has($cantDiariaNino) && $request->has($diasEntrega)){
                  $despensa->productos()->attach($productotodo->id, ['cantDiariaNino' => $request->$cantDiariaNino,'diasEntrega' => $request->$diasEntrega]);
            }
            //si esta relacionada
          }


      }


      return redirect()->action('DespensaController@show',$despensa);
    }

    public function destroy($id){
      //Se obtiene y elimina el producto deseada
      $despensa = Despensa::find($id)->delete();
      //Se ejecuta la función index de ProductoController
      return redirect()->action('DespensaController@index');
    }
    //Función para reactivar un producto con Softdelete
    public function habilitaDespensa($id){
      $despensa= Despensa::withTrashed()->find($id);
      $despensa->deleted_at=NULL;
      $despensa->save();
      return view('despensas.show')->with('despensa',$despensa);
    }





}

resources/views/despensas/create.blade.php
@extends('layouts.master')

@section('botones')
  <!-- Inicio del botón de guardado -->
  <div class="row">
    <button id="save" class="ui circular massive right floated teal save icon submit button" onclick="envio()">
    <i class="save icon"></i>
    </button>
  </div>
  <!-- Final del botón de guardado -->
  <div style="visibility:hidden">
    <br />..
  </div>
  <!-- Inicio del botón de regresar -->
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick="$('#regresar').modal('show');">
    <i class="chevron left icon"></i>
    </button>
  </div>
  <!-- Final del botón de guardado -->
@stop

@section('titulo_seccion')
  Crear Despensa
@stop


<?php $i=0;?>
@foreach($productos as $producto)
<?php $i++;
?>
@endforeach


@section('scripts')
  <script type="text/javascript">
    // Función para verificar si el form esta validado
    function envio(){
      //validacion de seleccion de al menos un producto
      var bandera = false;
      var php_countproductos = "<?php echo $i; ?>";
      for (var i = 1; i <= php_countproductos; i++) {
        var a = $( "input[name=cantDiariaNino"+i+"]").val();
        var b = $( "input[name=diasEntrega"+i+"]").val();

        if(a!="" && b!=""){
          bandera=true;
        }

      }
      //alert(bandera);
      if (bandera==true){
        $('#c').form('validate form');
        //Si es true, se mostrara el modal con el id "guardar"
        if($('#registro_form').form('is valid')){
          $('#guardar').modal('show');
        }
      }
      else{
        $('#mensajeProductos').show();
      }

    }
  </script>

  <script type="text/javascript">
    $(document).ready(function(){
      $('.segment').dimmer({
        on: 'hover'
      });
      //Inicialización de elementos de Semantic UI
      $('.ui.modal').modal();
      $('.menu .item').tab();
      $('select').dropdown();

      //Validaciones dentro de la forma con id "registro_form"

      $('#registro_form').form({
        on:'blur',
        inline: true,
        fields:{
          nombre:{
            identifier: 'programa_id',
            rules:[{
              type: 'empty',
              prompt: 'Seleccione un programa alimenticio'
            }]
          }
        }
      });

    });
  </script>
@stop

@section('contenido')

   <!--Inicio del Modal de confirmacion de regresar a index-->
  <div class="ui small modal" id="regresar">
    <i class="close icon"></i>
    <div class="ui icon header">
      <i class="archive icon"></i>
      Descartar registro
    </div>
    <div class=" content">
        <p>¿Estás seguro que deseas regresar?. Se perderan todos los datos sin guardar.</p>
    </div>
    <div class="actions">
      <div class="ui negative cancel button">
        <i class="remove icon"></i>
        No
      </div>
      <div class="ui positive button" onclick=window.location.href="{{route('despensa.index')}}">
        <i class="checkmark icon"></i>
        Si
      </div>
    </div>
  </div>
  <!--Final del Modal de confirmacion de regresar a index-->

  <!--Inicio del Modal de confirmacion de envio de formulario-->
  <div class="ui modal" id="guardar">
    <i class="close icon"></i>
    <div class="ui icon header">
      <i class="archive icon"></i>
      Guardar registro nuevo
    </div>
    <div class="content">
        <p>¿Deseas guardar el registro de la localidad?</p>
    </div>
    <div class="actions">
        <div class="ui negative cancel button">
          <i class="remove icon"></i>
          No
        </div>
        <button class="ui positive submit button" type="submit" form="registro_form">
          <i class="checkmark icon"></i>
          Si
        </button>
    </div>
  </div>
  <!--Final del Modal de confirmacion de envio de formulario-->

  <!--Inicio del Contenedor de forma de registro-->
  <div class="ui grid container">
    <div class="row">
      <div class="column">
        <!--Inicio de la forma de registro-->
        <form id="registro_form" class="ui form" action="{{route('despensa.store')}}" method="POST">
          <input type="hidden" name="_token" value="{{csrf_token()}}">
          <input type="hidden" name="_method" value="POST">
          <h4 class="ui horizontal divider header">
            <i class="food icon">
            </i>
            Detalles de despensa
          </h4>
          <div class="ui warning message hidden" id="mensajeProductos">
            <i class="close icon"></i>
            <div class="header">
              Debes agregar al menos un producto a la despensa!
            </div>
            Inserta cantidad por beneficiario y dias de entrega.
          </div>

          <!-- Inicio de la Seccion de datos generales -->
            <!-- Inicio de la primera fila -->
            <div class="one fields">


              <!-- Select para el campo de "Presentacion" -->
              <div class="six wide required field">
                <label class="prompt">Programa Alimenticio</label>
                <select class="ui fluid dropdown" name="programa_id">
                  <option value=""></option>
                  @foreach($programas as $programa)
                  <option value="{{$programa->id_programa}}">{{$programa->tipo}}</option>
                  @endforeach
                </select>
              </div>
            </div>
            <!-- Final de la primera fila -->

          <div class="row"></br></br></div>
          <!-- Final de la Seccion de datos generales -->
          <!--Inicio del contenidor de cartas-->
          <div class="ui five special  cards">
             @foreach($productos as $producto)



                <div class="ui card black blurring segment" >
                  <div class="ui inverted  dimmer">
                    <div class="content">
                      <div class="centered ">
                        <div class="ui grid">
                          <div class="two wide column ">
                          </div>
                          <div class="twelve wide column required field">
                            <label class="prompt">Cantidad diaria por niño</label>
                              <div class="ui mini right labeled input">
                                <input type="text" placeholder="" name="cantDiariaNino{{$producto->id}}">
                                <div class="ui basic label">
                                  {{$producto->unidad_de_medida->nombre}}
                                </div>
                              </div>

                          </div>
                        </div>

                        <div class="ui grid">
                          <div class="two wide column ">
                          </div>
                          <div class="twelve wide column required field">
                            <label class="prompt">Dias de entrega</label>
                            <div class="ui  input">
                              <input type="number" placeholder="" name="diasEntrega{{$producto->id}}">
                            </div>
                          </div>
                        </div>

                      </div>
                    </div>
                  </div>
                   <div class="content">

                      <div class="header">{{$producto->nombre}}
                        <div class="ui meta">
                          <span class="date">{{$producto->marca}}
                          </span>
                        </div>
                      </div>
                   </div>

                   <div class="content ">
                      <!-- Subtitulo para mostrar la marca del producto -->

                      <!-- Renglón para mostrar el Provedor del producto -->

                      <div class="content">
                         <span class="right floated">

                           xxxx
                         </span>

                         Proveedor
                       </div>
                       </br>
                       <div class="content">
                          <span class="right floated">

                            {{$producto->contenido_neto}}{{$producto->unidad_de_medida->nombre}}
                          </span>

                          Contenido Neto
                        </div>
                        </br>
                        <div class="content">
                           <span class="right floated">

                             {{$producto->masa_drenada}}{{$producto->unidad_de_medida->nombre}}
                           </span>

                           Masa Drenada
                       </div>



                   </div>
                   <div class="extra content">
                     <span class="right floated">
                       ${{$producto->precio}}
                     </span>
                     <span>
                       {{$producto->presentacion->nombre}}
                     </span>
                  </div>

                </div>
                <!-- Fin de la carta -->
             @endforeach
          </div>
          <!--Fin del contenidor de cartas-->
        </form>
        <!--Final de la forma de registro-->
      </div>
    </div>
  </div>
  <!--Final del Contenedor de forma de registro-->
@stop

resources/views/despensas/index.blade.php
@extends('layouts.master')

@section('botones')
  <!-- Inicio del botón crear -->
  <button class="ui circular massive right floated pink plus icon button" onclick=window.location.href="{{route('despensa.create')}}">
    <i class="plus icon"></i>
  </button>
  <!-- Fin del botón crear -->
@stop

@section('titulo_seccion')
  Despensas
@stop

@section('scripts')
  <script type="text/javascript">
    $( document ).ready(function() {
      //Ocultar tabla con despensas activas/inactivas
      $(".hidden").hide();
    });
  </script>
  <script>
  /*Función para mostrar la tabla de despensas activas y ocultar
    activas/inactivas y viceversa*/
    function eliminados(){
      if($('.ui.checkbox').checkbox('is checked')){
        $(".hidden").show();
      }else{
        $(".hidden").hide();
      }
    }
  </script>
@stop

@section('contenido')
<!--Inicio de container independiente de tablas-->
<div class="ui grid container">
 <div class="row">
   <div class="twelve wide column"></div>
   <div class="four wide column">
     <!-- Checkbox para mostrar las diferentes tablas -->
     <div class=" ui slider checkbox ">
       <input type="checkbox" name="eliminados" value="1" onchange="eliminados()">
       <label>Mostrar eliminadas</label>
     </div>
   </div>
 </div>
</div>

<!--Inicio del contenidor de cartas-->
   <div class="ui four cards">
      @foreach($despensas as $despensa)

         @if($despensa->deleted_at != NULL)
         <!-- Inicio de la carta -->
         <div class="ui card red hidden" onclick=window.location.href="{{route('despensa.show', $despensa->id_despensa)}}">
            <div class="content">
               <div class="ui red right ribbon label">
                  <i class="trash icon"></i> Eliminado
               </div>
         @else
         <div class="ui card green" onclick=window.location.href="{{route('despensa.show', $despensa->id_despensa)}}">
            <div class="content">
               <div class="ui green right ribbon label">
                  <i class="save icon"></i> Activa
               </div>
         @endif



            <div class="header"></br>{{$despensa->programa->tipo}}</div>
            </div>

            <div class="content">

               <!-- Subtitulo para mostrar la marca del producto -->

               <div class="meta">
                  Despensa #{{$despensa->id_despensa}}
                </div>
               <h4 class="ui sub header">Fecha de creación:</br></br><?php
               $date = date('d-m-Y, g:i a',strtotime($despensa->created_at));
               echo $date;
                ?></h4>
               <div class="ui small feed">
                  <!-- Renglón para mostrar el Provedor del producto -->
                  <div class="event"><div class="content"><div class="summary">
                  <div class="extra content">

                    <span>
                      <?php $i=0 ?>
                      @foreach($despensa->productos as $producto)
                      <?php $i++ ?>
                      @endforeach
                      <i class="food icon"></i>
                      <?php echo($i) ?> productos
                    </span>
                  </div>
                  </div></div></div>



               </div>
            </div>

         </div>
         <!-- Fin de la carta -->

      @endforeach
   </div>
   <!--Fin del contenidor de cartas-->
   <br>
   <div class="ui right floated pagination menu">
      <a href="{!! $despensas->previousPageUrl() !!}" class="icon item">
         <i class="left chevron icon "></i>
      </a>
      @for($pages = 1; $pages <= $despensas->lastPage(); $pages++)
      <a href="{!! $despensas->url($pages) !!}" class="item ">{{$pages}}</a>
      @endfor
      <a href="{!! $despensas->nextPageUrl() !!}" class="icon item">
         <i class="right chevron icon "></i>
      </a>
   </div>


@stop

resources/views/despensas/show.blade.php
@extends('layouts.master')

@section('botones')
   <!-- Inicio botón para editar -->
   <div class="row">
   @if($despensa->deleted_at == NULL)
     <button class="  ui circular massive right floated teal write icon submit button"  onclick=window.location.href="{{route('despensa.edit', $despensa->id_despensa)}}">
   @else
     <button class="  ui circular massive right floated teal write icon submit disabled button"  onclick=window.location.href="{{route('despensa.edit', $despensa->id_despensa)}}">
   @endif
       <i class="write icon"></i>
     </button>
   </div>
  <!-- Final botón para editar -->

  <div style="visibility:hidden">
    <br />..
  </div>
  <!-- Inicio del botón de eliminar o rehabilitar, siendo el caso -->
  <div class="row">
  @if($despensa->deleted_at == NULL)
    <button class="  ui circular massive right floated teal trash outline icon button" onclick="$('#eliminar').modal('show');" >
      <i class="trash outline icon"></i>
  @else
    <button class="  ui circular massive right floated teal undo icon button" onclick="$('#habilitar').modal('show');" >
      <i class=" undo icon"></i>
  @endif
    </button>
  </div>
  <!-- Fin del botón de eliminar o rehabilitar, siendo el caso -->

  <div style="visibility:hidden">
    <br />..
  </div>

  <!-- Inicio de botón de regresar al index -->
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick=window.location.href="{{route('despensa.index')}}">
      <i class="chevron left icon"></i>
    </button>
  </div>
  <!-- Fin de botón de regresar al index -->
@stop

@section('titulo_seccion')
  Despensa #{{$despensa->id_despensa}}
@stop

@section('scripts')
   <script>
      $( document ).ready(function() {
         // Inicialización de elementos de Semantic UI
         $('.ui.accordion').accordion();
         $('.ui.modal').modal();
      });
   </script>
@stop

@section('contenido')

   <!-- Inicio del Modal de confirmacion de regreso a index -->
   <div class="ui small modal" id="eliminar">
      <i class="close icon"></i>
      <div class="ui icon header">
         <i class="archive icon"></i>
         Eliminar Despensa
      </div>
      <div class=" content">
        <p>¿Seguro que deseas eliminar la despensa #{{$despensa->id_despensa}} {{$despensa->programa->tipo}} ?</p>
      </div>
      <div class="actions">
           <div class="ui negative cancel button">
             <i class="remove icon"></i>
             No
           </div>
           <button class="ui positive submit button "  type="submit" form="vista" value="delete">
             <i class="checkmark icon"></i>
             Si
           </button>
      </div>
   </div>
   <!-- Final del Modal de confirmacion de regreso a index -->

   <!-- Inicio del Modal de confirmacion de habilitacion de producto -->
   <div class="ui small modal" id="habilitar">
       <i class="close icon"></i>
       <div class="ui icon header">
          <i class="archive icon"></i>
          Reactivar despensa
       </div>
       <div class=" content">
          <p>¿Seguro que deseas reactivar la despensa #{{$despensa->id_despensa}}  {{$despensa->programa->tipo}}?</p>
       </div>
       <div class="actions">
           <div class="ui negative cancel button">
              <i class="remove icon"></i>
              No
           </div>
           <button class="ui positive submit button " onclick=window.location.href="{{route('habilitaDespensa',$despensa->id_despensa)}}">
              <i class="checkmark icon"></i>
              Si
           </button>
       </div>
   </div>
   <!-- Final del Modal de confirmacion de habilitacion de producto -->

   <!--Inicio de forma de visualizacion que utiliza el metodo destroy para eliminar Producto-->
   <form id="vista" class="ui form" action="{{route('despensa.destroy', $despensa->id_despensa)}}" method="POST" >
      <input type="hidden" name="_token" value="{{csrf_token()}}">
      <input type="hidden" name="_method" value="DELETE">
      <h4 class="ui horizontal divider header">
        <i class="food icon">
        </i>
        Programa {{$despensa->programa->tipo}}
      </h4>
      <?php $i=0 ?>
      @foreach($despensa->productos as $producto)
      <?php $i++ ?>
      @endforeach
      <?php if ($i==0): ?>
        <div class="ui negative message"><i class="info circle icon"></i>La despensa no tiene productos asignados.</div>
      <?php else: ?>
        @if($despensa->deleted_at == NULL)
           <div class="ui message"><i class="info circle icon"></i>Información de la Despensa </div>
        @else
           <div class="ui negative message"><i class="info circle icon"></i>Despensa deshabilitada. Para editar deshacer eliminación. </div>
        @endif
      <?php endif; ?>




      <!--Inicio del contenidor de cartas-->
         <div class="ui five cards">

            @foreach($despensa->productos as $producto)
              <div class="ui card black" >

                 <div class="content">

                    <div class="header">{{$producto->nombre}}
                      <div class="ui meta">
                        <span class="date">{{$producto->marca}}
                        </span>
                      </div>
                    </div>
                 </div>

                 <div class="ui segments content">
                    <!-- Subtitulo para mostrar la marca del producto -->
                       <!-- Renglón para mostrar el Provedor del producto -->
                       <div class="ui segment">
                       <div class=" content">
                          <span class="right floated">
                            xxxx
                          </span>
                          Proveedor
                        </div>

                        <div class=" content">
                           <span class="right floated">
                             {{$producto->contenido_neto}}{{$producto->unidad_de_medida->nombre}}
                           </span>
                           Contenido Neto
                         </div>

                         <div class=" content">
                            <span class="right floated">
                              {{$producto->masa_drenada}}{{$producto->unidad_de_medida->nombre}}
                            </span>
                            Masa Drenada
                        </div>
                        </div>
                        <div class="ui segment">
                          <div class=" ">
                             <span class="right floated">

                               <strong>{{$producto->pivot->cantDiariaNino}}{{$producto->unidad_de_medida->nombre}}</strong>
                             </span>
                             <strong>Cantidad diaria </strong>
                           </div>
                           </br>
                           <div class="">
                              <span class="right floated">
                                <strong>
                                {{$producto->pivot->diasEntrega}}{{$producto->unidad_de_medida->nombre}}
                              </strong>
                              </span>
                            <strong>Dias de entrega</strong>
                          </div>
                        </div>
                 </div>
                 <div class="extra content">
                   <span class="right floated">
                     ${{$producto->precio}}
                   </span>
                   <span>
                     {{$producto->presentacion->nombre}}
                   </span>
                </div>

              </div>
              <!-- Fin de la carta -->

            @endforeach
         </div>
         <!--Fin del contenidor de cartas-->

   </form>
   <!--Final de forma de visualizacion que utiliza el metodo destroy para eliminar Producto-->
@stop