app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::resource('foodprogram','FoodProgramController');

Route::group(['middleware' => ['web']], function () {
    //
});


Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'HomeController@index');
    Route::resource('usuario', 'UsuarioController');
    Route::get('/perfil', [
      'as' => 'profile', 'uses' => 'UsuarioController@perfil']);

    Route::get('/usuario/habilitar/{id}', 'UsuarioController@habilitaUsuario')->name('habilitaUsuario');
    Route::get('/perfil/{id}', 'UsuarioController@perfil')->name('perfil');

    //Carla
    Route::resource('escuela','EscuelaController');
    //Route::get('escuela/reac/{id}', 'EscuelaController@habilitaEscuela');
    Route::get('/escuela/habilitar/{id}', 'EscuelaController@habilitaEscuela')->name('habilitaEscuela');

    Route::resource('despensa','DespensaController');
    Route::get('/despensa/habilitar/{id}', 'DespensaController@habilitaDespensa')->name('habilitaDespensa');



    //Armando Productos
    Route::resource('producto', 'ProductoController');
    Route::get('producto/reac/{id}', 'ProductoController@reactivate');

    //Armando
    Route::resource('localidad', 'LocalidadController');
    Route::get('localidad/reac/{id}', 'LocalidadController@reactivate');


    //Alejandro
    Route::resource('programa','ProgramaController');
    Route::get('programa/reac/{id}', 'ProgramaController@habilitaPrograma');

    Route::resource('provedor','ProvedorController');
    Route::get('provedor/reac/{id}', 'ProvedorController@habilitaProvedor');

    Route::resource('contrato','ContratoController');
    Route::get('contrato/reac/{id}', 'ContratoController@habilitaContrato');

    //Armando, Ordenes
    Route::resource('ordenes','OrdendeComprasController');


});

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;
use App\Municipio;
use DB;

class UsuarioController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $todos = User::withTrashed()->paginate(12);
      $usuarios = User::paginate(12);
      return view('usuarios.index',['todos'=>$todos, 'usuarios' => $usuarios]);
    }

    public function show($id){
      $usuario = User::withTrashed()->find($id);
      return view('usuarios.show')->with('usuario',$usuario);
    }

    public function create(){
      $municipios = Municipio::all();
      return view('usuarios.create')->with('municipios', $municipios);
    }

    public function edit($id){
      $municipios = Municipio::all();
      $usuario= User::find($id);
      return view('usuarios.edit', ['municipios'=> $municipios, 'usuario'=>$usuario]);
    }

    public function destroy($id){
      $usuario= User::find($id)->delete();
      $usuario = User::withTrashed()->find($id);
      return redirect()->action('UsuarioController@show',$usuario);
    }

    public function store(Request $request){
      $request->merge(['password' => bcrypt($request->password)]);
      $inputs = $request->all();
      $usuario = User::create($inputs);
      $usuario->save();
      return redirect()->action('UsuarioController@index');
    }


    public function habilitaUsuario($id){
      $usuario = User::withTrashed()->find($id);
      $usuario->deleted_at=NULL;
      $usuario->save();
      return redirect()->action('UsuarioController@show',$usuario);
    }

    public function update($id, Request $request){
      $nueva_pass = $request->get('password');
      $usuario = User::find($id);

      if(empty($nueva_pass)){
        $usuario->update($request->except('password'));
      }else{
        $request->merge(['password' => bcrypt($request->password)]);
        $inputs = $request->all();
        $usuario->update($request->all());
      }

      return redirect()->action('UsuarioController@show',$id);
    }

    public function perfil($id){
      $usuario = User::find($id);
      return view('usuarios.show')->with('usuario',$usuario);
    }


}

resources/views/usuarios/create.blade.php
@extends('layouts.master')

@section('titulo_seccion')
  Crear Usuario
@endsection

@section('scripts')

  <script type="text/javascript">
  function envio(){
    $('.ui.form').form('validate form');
    if ($('.ui.form').form('is valid')){
      $('#guardar').modal('show');
    }

  }

  </script>

  <script type="text/javascript">

  $(function() {
    $('.ui.form').form({
      on:'blur',
      inline:true,
      fields: {
        nombre: {
          identifier  : 'nombre',
          rules: [
            {
              type   : 'empty',
              prompt : 'El nombre es necesario'
            }
          ]
        },
        apellido_p: {
         identifier  : 'apellido_p',
         rules: [
           {
             type   : 'empty',
             prompt : 'El apellido paterno es necesario'
           }
         ]
        },
        apellido_m: {
          identifier  : 'apellido_m',
          rules: [
            {
              type   : 'empty',
              prompt : 'El apellido materno es necesario'
            }
          ]
        },
        email: {
         identifier  : 'email',
         rules: [
           {
             type   : 'empty',
             prompt : 'El email es necesario'
           },
           {
             type   : 'email',
             prompt : 'El email {value} no es válido'
           }
         ]
        },
        municipio_id: {
          identifier  : 'municipio_id',
          rules: [
            {
              type   : 'empty',
              prompt : 'Por favor selecciona un municipio'
            }
          ]
        },
        tipo_usuario: {
          identifier  : 'tipo_usuario',
          rules: [
            {
              type   : 'empty',
              prompt : 'Por favor selecciona un rol'
            }
          ]
        },
        password: {
          identifier  : 'password',
          rules: [
            {
              type   : 'empty',
              prompt : 'Escribe una contraseña'
            },
            {
              type   : 'minLength[6]',
              prompt : 'La contraseña debe tener al menos 6 caracteres'
            }
          ]
        },
        confirm_pass: {
          identifier  : 'confirm_pass',
          rules: [
            {
              type   : 'empty',
              prompt : 'Vuelve a escribir la contraseña'
            },
            {
              type   : 'match[password]',
              prompt : 'Las contraseñas no coinciden'
            }
          ]
        },
      }
    });
  });
  </script>
@endsection


@section('botones')
  <div class="row">
    <button class="  ui circular massive right floated teal save icon submit button" onclick="envio()">
    <i class="save icon"></i>
    </button>
  </div>
  <br />
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick="$('#regresar').modal('show');">
    <i class="chevron left icon"></i>
    </button>
  </div>
@endsection

@section('contenido')


<!--Modal de confirmacion de regresar a index-->
<div class="ui small modal" id="regresar">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="archive icon"></i>
    Descartar registro
  </div>
  <div class=" content">
      <p>¿Estás seguro que deseas regresar?. Se perderan todos los campos.</p>
  </div>
  <div class="actions">
    <div class="ui negative   button">
      <i class="remove icon"></i>
      No
    </div>
    <div class="ui positive  button" onclick=window.location.href="{{route('usuario.index')}}">
      <i class="checkmark icon"></i>
      Si
    </div>
  </div>
</div>



<!--Modal de confirmacion de envio de formulario-->
<div class="ui small modal" id="guardar">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="archive icon"></i>
    Guardar cambios
  </div>
  <div class="content">
      <p>¿Deseas guardar el registro de usuario?</p>
  </div>
  <div class="actions">
      <div class="ui red cancel button">
        <i class="remove icon"></i>
        No
      </div>
      <button class="ui green ok submit  button"  type="submit" form="registro">
        <i class="checkmark icon"></i>
        Si
      </button>
  </div>
</div>


  <form id="registro" action="{{route('usuario.store')}}" class="ui form" method="post">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    
    <div class="field">
      <label class="prompt">Nombre Completo</label>
      <div class="three fields">
        <div class="field">
          <input type="text" name="nombre" placeholder="Juan Pablo">
        </div>
        <div class="field">
          <input type="text" name="apellido_p" placeholder="López">
        </div>
        <div class="field">
          <input type="text" name="apellido_m" placeholder="Martínez">
        </div>
      </div>
    </div>
    <div class="field">
      <div class="three fields">
        <div class="field">
          <label>Correo Electónico</label>
          <input type="text" name="email" placeholder="juan.lopez@queretaro.gob.mx">
        </div>
        <div class="field">
          <label>Responsable de Municipio</label>
          <select class="ui fluid dropdown" name="municipio_id">
            <option></option>
            @foreach($municipios as $municipio)
              <option value="{{$municipio->id}}">{{$municipio->nombre}}</option>
            @endforeach
          </select>
        </div>
        <div class="field">
          <label>Rol de Usuario</label>
          <select class="ui fluid dropdown" name="tipo_usuario">
            <option></option>
            <option value="1">Administrador</option>
            <option value="2">Central - DIF Estatal</option>
            <option value="3">Foráneo - DIF Municipal</option>
          </select>
        </div>
      </div>
    </div>
    <div class="field">
      <div class="two fields">
        <div class="field">
          <label>Contraseña</label>
          <input type="password" name="password" />
        </div>
        <div class="field">
          <label>Confirmar Contraseña</label>
          <input type="password" name="confirm_pass" />
        </div>
      </div>
    </div>
  </form>
@endsection

resources/views/usuarios/edit.blade.php
@extends('layouts.master')

@section('titulo_seccion')
  Editando usuario : {{$usuario->nombre}}  {{$usuario->apellido_p}} {{$usuario->apellido_m}}
@endsection

@section('scripts')

  <script type="text/javascript">
  function envio(){
    $('.ui.form').form('validate form');
    if ($('.ui.form').form('is valid')){
      $('#guardar').modal('show');
    }

  }

  </script>

  <script type="text/javascript">

  $(function() {
    $('.ui.form').form({
      on:'blur',
      inline:true,
      fields: {
        nombre: {
          identifier  : 'nombre',
          rules: [
            {
              type   : 'empty',
              prompt : 'El nombre es necesario'
            }
          ]
        },
        apellido_p: {
         identifier  : 'apellido_p',
         rules: [
           {
             type   : 'empty',
             prompt : 'El apellido paterno es necesario'
           }
         ]
        },
        apellido_m: {
          identifier  : 'apellido_m',
          rules: [
            {
              type   : 'empty',
              prompt : 'El apellido materno es necesario'
            }
          ]
        },
        email: {
         identifier  : 'email',
         rules: [
           {
             type   : 'empty',
             prompt : 'El email es necesario'
           },
           {
             type   : 'email',
             prompt : 'El email {value} no es válido'
           }
         ]
        },
        municipio_id: {
          identifier  : 'municipio_id',
          rules: [
            {
              type   : 'empty',
              prompt : 'Por favor selecciona un municipio'
            }
          ]
        },
        tipo_usuario: {
          identifier  : 'tipo_usuario',
          rules: [
            {
              type   : 'empty',
              prompt : 'Por favor selecciona un rol'
            }
          ]
        },
        password: {
          identifier  : 'password',
          optional   : true,
          rules: [
            {
              type   : 'minLength[6]',
              prompt : 'La contraseña debe tener al menos 6 caracteres'
            }
          ]
        },
        confirm_pass: {
          identifier  : 'confirm_pass',
          rules: [
            {
              type   : 'match[password]',
              prompt : 'Las contraseñas no coinciden'
            }
          ]
        },
      }
    });
  });
  </script>
@endsection


@section('botones')
  <div class="row">
    <button class="ui circular massive right floated teal save icon submit button" onclick="envio()" >
    <i class="save icon"></i>
    </button>
  </div>
  <div style="visibility:hidden">
    <br />..
  </div>
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick="$('#regresar').modal('show');">
    <i class="chevron left icon"></i>
    </button>
  </div>
@endsection

@section('contenido')


<!--Modal de confirmacion de regreso a show-->
<div class="ui small modal" id="regresar">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="archive icon"></i>
    Descartar registro
  </div>
  <div class=" content">
      <p>¿Estás seguro que deseas regresar?. Se perderan todos los campos.</p>
  </div>
  <div class="actions">

    <div class="ui red cancel button">
      <i class="remove icon"></i>
      No
    </div>
    <div class="ui green ok button" onclick=window.location.href="{{route('usuario.show', $usuario->id)}}">
      <i class="checkmark icon"></i>
      Yes
    </div>
  </div>
</div>
<!--Modal de confirmacion de envio de modificaciones-->
<div class="ui small modal" id="guardar">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="archive icon"></i>
    Guardar cambios
  </div>
  <div class="content">
      <p>¿Deseas guardar los cambios en escuela {{$usuario->nombre}}?</p>
  </div>
  <div class="actions">
      <div class="ui red cancel button">
        <i class="remove icon"></i>
        No
      </div>
      <button class="ui green ok submit button" type="submit" form="editar">
        <i class="checkmark icon"></i>
        Si
      </button>
  </div>
</div>


  <form id="editar" action="{{route('usuario.update',$usuario->id)}}" class="ui form" method="post">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    {{method_field('PATCH')}}

    <div class="field">
      <label class="prompt">Nombre Completo</label>
      <div class="three fields">
        <div class="field">
          <input type="text" name="nombre" placeholder="Juan Pablo" value="{{$usuario->nombre}}">
        </div>
        <div class="field">
          <input type="text" name="apellido_p" placeholder="López" value="{{$usuario->apellido_p}}">
        </div>
        <div class="field">
          <input type="text" name="apellido_m" placeholder="Martínez" value="{{$usuario->apellido_m}}">
        </div>
      </div>
    </div>
    <div class="field">
      <div class="three fields">
        <div class="field">
          <label>Correo Electónico</label>
          <input type="text" name="email" placeholder="juan.lopez@queretaro.gob.mx" value="{{$usuario->email}}">
        </div>
        <div class="field">
          <label>Responsable de Municipio</label>
          <select class="ui fluid dropdown" name="municipio_id">
            <option></option>
            @foreach($municipios as $municipio)
              @if($usuario->municipio_id == $municipio->id)
                <option selected value="{{$municipio->id}}">{{$municipio->nombre}}</option>
              @else
                <option value="{{$municipio->id}}">{{$municipio->nombre}}</option>
              @endif
            @endforeach
          </select>
        </div>
        <div class="field">
          <label>Rol de Usuario</label>
          <select class="ui fluid dropdown" name="tipo_usuario">
            <option></option>
            @if($usuario->tipo_usuario == 1)
              <option selected value="1">Administrador</option>
              <option value="2">Central - DIF Estatal</option>
              <option value="3">Foráneo - DIF Municipal</option>
            @elseif($usuario->tipo_usuario == 2)
              <option value="1">Administrador</option>
              <option value="2">Central - DIF Estatal</option>
              <option selected value="3">Foráneo - DIF Municipal</option>
            @elseif($usuario->tipo_usuario == 3)
              <option value="1">Administrador</option>
              <option value="2">Central - DIF Estatal</option>
              <option selected value="3">Foráneo - DIF Municipal</option>
            @endif

          </select>
        </div>
      </div>
    </div>
    <div class="field">
      <div class="two fields">
        <div class="field">
          <label>Nueva Contraseña</label>
          <input type="password" name="password" />
        </div>
        <div class="field">
          <label>Confirmar Contraseña</label>
          <input type="password" name="confirm_pass" />
        </div>
      </div>
    </div>
  </form>
@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.master')

  @section('scripts')
    <script type="text/javascript">
      $( document ).ready(function() {
        $("#todos").hide();
        $("#usuarios").show();
      });
    </script>
    <script>
      function eliminados(){
        if($('.ui.checkbox').checkbox('is checked')){
          $("#todos").show();
          $("#usuarios").hide();
        }else{
          $("#usuarios").show();
          $("#todos").hide();
        }
      }
    </script>
  @stop

  @section('titulo_seccion')
    Usuarios
  @stop


  @section('botones')
    @can('crearEscuela')
      <button class="ui circular massive right floated pink plus icon button" onclick=window.location.href="{{route('usuario.create')}}">
      <i class="plus icon"></i>
      </button>
    @endcan
  @stop

  @section('contenido')
    <!--Inicio de container independiente de tablas-->
    <div class="ui grid container">
      <div class="row">
        <div class="twelve wide column"></div>
        <div class="four wide column">
          <div class=" ui slider checkbox ">
            <input type="checkbox" name="eliminados" value="1" onchange="eliminados()">
            <label>Mostrar eliminadas</label>
          </div>
        </div>
      </div>
    </div>



    <table class="ui selectable sortable teal celled table" id="todos">
      <thead>
        <tr>
          <th class="four wide">Nombre</th>
          <th class="two wide">Apellido Paterno</th>
          <th class="two wide">Apellido Materno</th>
          <th class="two wide">Email</th>
          <th class="two wide">Tipo Usuario</th>
          <th class="two wide">Municipio</th>
          <th class="one wide">Ver</th>
        </tr>
      </thead>
      <tbody>
        @foreach($todos as $usuario)
          @if($usuario->deleted_at!=NULL)
            <tr class="negative">
          @else
            <tr class="positive">
          @endif
            <td>
              {{$usuario->nombre}}
            </td>
            <td>{{$usuario->apellido_p}}</td>
            <td>{{$usuario->apellido_m}}</td>
            <td>{{$usuario->email}}   </td>
            <td> @if($usuario->tipo_usuario==1)
                    Admin
                  @elseif($usuario->tipo_usuario==2)
                    Central
                  @else
                    Foráneo
                  @endif
            </td>
            <td> {{$usuario->municipio->nombre}}</td>
             <td onclick=window.location.href="{{route('usuario.show', $usuario->id)}}" class=" selectable center aligned">
                <i class="info circle big icon "></i>
             </td>
          </tr>
        @endforeach
      </tbody>
      <tfoot>
        <tr>
          <th colspan="7">
            <div class="ui right floated pagination menu">
              <a href="{!! $todos->previousPageUrl() !!}" class="icon item">
                <i class="left chevron icon "></i>
              </a>
              @for ($pages = 1; $pages <= $todos->lastPage(); $pages++)
                  <a href="{!! $todos->url($pages) !!}" class="item ">{{$pages}}</a>
              @endfor
              <a href="{!! $todos->nextPageUrl() !!}" class="icon item">
                <i class="right chevron icon "></i>
              </a>
            </div>
          </th>
        </tr>
      </tfoot>
    </table>

    <table class="ui selectable sortable teal celled table" id="usuarios">
      <thead>
        <tr>
          <th class="four wide">Nombre</th>
          <th class="two wide">Apellido Paterno</th>
          <th class="two wide">Apellido Materno</th>
          <th class="two wide">Email</th>
          <th class="two wide">Tipo Usuario</th>
          <th class="two wide">Municipio</th>
          <th class="one wide">Ver</th>
        </tr>
      </thead>
      <tbody>
        @foreach($usuarios as $usuario)
            <tr>
            <td>
              {{$usuario->nombre}}
            </td>
            <td>{{$usuario->apellido_p}}</td>
            <td>{{$usuario->apellido_m}}</td>
            <td>{{$usuario->email}}   </td>
            <td> @if($usuario->tipo_usuario==1)
                    Admin
                  @elseif($usuario->tipo_usuario==2)
                    Central
                  @else
                    Foráneo
                  @endif
            </td>
            <td>{{$usuario->municipio->nombre}}</td>
             <td onclick=window.location.href="{{route('usuario.show', $usuario->id)}}" class=" selectable center aligned">
                <i class="info circle big icon "></i>
             </td>
          </tr>
        @endforeach
      </tbody>
      <tfoot>
        <tr>
          <th colspan="7">
            <div class="ui right floated pagination menu">
              <a href="{!! $todos->previousPageUrl() !!}" class="icon item">
                <i class="left chevron icon "></i>
              </a>
              @for ($pages = 1; $pages <= $todos->lastPage(); $pages++)
                  <a href="{!! $todos->url($pages) !!}" class="item ">{{$pages}}</a>
              @endfor
              <a href="{!! $todos->nextPageUrl() !!}" class="icon item">
                <i class="right chevron icon "></i>
              </a>
            </div>
          </th>
        </tr>
      </tfoot>
    </table>
  @stop

resources/views/usuarios/show.blade.php
@extends('layouts.master')


@section('titulo_seccion')
  Usuario
@endsection




@section('botones')
  <div class="row">
    @can('editarEscuela')
      @if($usuario->deleted_at==NULL)
      <button class="  ui circular massive right floated teal write icon submit button"  onclick=window.location.href="/usuario/{{$usuario->id}}/edit">
      @else
      <button class="  ui circular massive right floated teal write icon submit disabled button"  onclick=window.location.href="/usuario/{{$usuario->id}}/edit">
      @endif
      <i class="write icon"></i>
      </button>
    @endcan
  </div>
  <div style="visibility:hidden">
    <br />..
  </div>
  <div class="row">

    @if($usuario->deleted_at==NULL)
        <button class="  ui circular massive right floated teal trash outline icon button" onclick="$('#eliminar').modal('show');" >
        <i class="trash outline icon"></i>
    @else
        <button class="  ui circular massive right floated teal undo icon button" onclick="$('#habilitar').modal('show');" >
        <i class=" undo icon"></i>
    @endif
    </button>
  </div>
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick=window.location.href="{{route('usuario.index')}}">
    <i class="chevron left icon"></i>
    </button>
  </div>
@stop







@section('contenido')
<!--Modal de confirmacion de regreso a index-->
<div class="ui small modal" id="eliminar">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="archive icon"></i>
    Eliminar Usuario
  </div>
  <div class=" content">
    <p>¿Seguro que deseas eliminar el usuario {{$usuario->nombre}}?</p>
  </div>
  <div class="actions">
      <div class="ui red  cancel button">
        <i class="remove icon"></i>
        No
      </div>
      <button class="ui green ok submit button "  type="submit" form="vista" value="delete">
        <i class="checkmark icon"></i>
        Si
      </button>
  </div>
</div>


<!--Modal de confirmacion de habilitacion de escuela-->
<div class="ui small modal" id="habilitar">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="archive icon"></i>
    Reactivar Escuela
  </div>
  <div class=" content">
    <p>¿Seguro que deseas reactivar la escuela {{$usuario->nombre}} con email : {{$usuario->email}}?</p>
  </div>
  <div class="actions">
      <div class="ui red  cancel button">
        <i class="remove icon"></i>
        No
      </div>
      <button class="ui green ok submit button " onclick=window.location.href="{{route('habilitaUsuario',$usuario->id)}}">
        <i class="checkmark icon"></i>
        Si
      </button>
  </div>
</div>



<form id="vista" method="post" action="{{route('usuario.destroy',$usuario->id)}}">


    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    {{method_field('DELETE')}}
    <div class="ui card centered">
      <div class="image">
        <img src="{{asset('img/avatar.jpg')}}"/>
      </div>
      <div class="content">
        <div class="header">
          {{$usuario->nombre}}   {{$usuario->apellido_p}}  {{$usuario->apellido_m}}
        </div>
        <div class="meta">
          {{$usuario->email}}
        </div>
        <div class="description">

          @if($usuario->tipo_usuario==1)
            Ubicado en : {{$usuario->municipio->nombre}}
          @elseif($usuario->tipo_usuario==2)
            Ubicado en : {{$usuario->municipio->nombre}}
          @else
            Responsable de  : {{$usuario->municipio->nombre}}
          @endif
           <br />

          Rol:
          @if($usuario->tipo_usuario==1)
            Admin
          @elseif($usuario->tipo_usuario==2)
            Central
          @else
            Foráneo
          @endif

        </div>

      </div>
    </div>
  </form>
@endsection