app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::resource('foodprogram','FoodProgramController');

Route::group(['middleware' => ['web']], function () {
    //
});


Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'HomeController@index');
    Route::resource('usuario', 'UsuarioController');
    Route::get('/perfil', [
      'as' => 'profile', 'uses' => 'UsuarioController@perfil']);

    Route::get('/usuario/habilitar/{id}', 'UsuarioController@habilitaUsuario')->name('habilitaUsuario');
    Route::get('/perfil/{id}', 'UsuarioController@perfil')->name('perfil');

    //Carla
    Route::resource('escuela','EscuelaController');
    //Route::get('escuela/reac/{id}', 'EscuelaController@habilitaEscuela');
    Route::get('/escuela/habilitar/{id}', 'EscuelaController@habilitaEscuela')->name('habilitaEscuela');

    Route::resource('despensa','DespensaController');
    Route::get('/despensa/habilitar/{id}', 'DespensaController@habilitaDespensa')->name('habilitaDespensa');



    //Armando Productos
    Route::resource('producto', 'ProductoController');
    Route::get('producto/reac/{id}', 'ProductoController@reactivate');

    //Armando
    Route::resource('localidad', 'LocalidadController');
    Route::get('localidad/reac/{id}', 'LocalidadController@reactivate');


    //Alejandro
    Route::resource('programa','ProgramaController');
    Route::get('programa/reac/{id}', 'ProgramaController@habilitaPrograma');

    Route::resource('provedor','ProvedorController');
    Route::get('provedor/reac/{id}', 'ProvedorController@habilitaProvedor');

    Route::resource('contrato','ContratoController');
    Route::get('contrato/reac/{id}', 'ContratoController@habilitaContrato');

    //Armando, Ordenes
    Route::resource('ordenes','OrdendeComprasController');


});

resources/views/ordenes/create.blade.php
@extends('layouts.master')

@section('botones')
  <!-- Inicio del botón de guardado -->
  <div class="row">
    <button id="save" class="ui circular massive right floated teal save icon submit button" onclick="envio()">
    <i class="save icon"></i>
    </button>
  </div>
  <!-- Final del botón de guardado -->
  <div style="visibility:hidden">
    <br />..
  </div>
  <!-- Inicio del botón de regresar -->
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick="$('#regresar').modal('show');">
    <i class="chevron left icon"></i>
    </button>
  </div>
  <!-- Final del botón de guardado -->
@stop

@section('titulo_seccion')
  Registrar Orden de Compra
@stop

@section('scripts')
  <script type="text/javascript">
    // Función para verificar si el form esta validado
    function envio(){
      $('#registro_form').form('validate form');
      //Si es true, se mostrara el modal con el id "guardar"
      if($('#registro_form').form('is valid')){
        $('#guardar').modal('show');
      }
    }
  </script>

  <script type="text/javascript">
    $(document).ready(function(){
      //Inicialización de elementos de Semantic UI
      $('.ui.modal').modal();
      $('.menu .item').tab();
      $('select').dropdown();
      //Validaciones dentro de la forma con id "registro_form"
      $('#registro_form').form({
        inline: true,
        fields:{
          no_folio:{
            identifier: 'no_folio',
            rules:[{
              type: 'empty',
              prompt: 'Número de folio necesario'
            }]
          },
          programa_id:{
            identifier: 'programa_id',
            rules:[{
              type: 'empty',
              prompt: 'Seleccione un programa'
            }]
          },
          municipio_id:{
            identifier: 'municipio_id',
            rules:[{
              type: 'empty',
              prompt: 'Seleccione un municipio'
            }]
          },
          mes:{
            identifier: 'mes',
            rules:[{
              type: 'empty',
              prompt: 'Seleccione un mes'
            }]
          },
          anio:{
            identifier: 'anio',
            rules:[{
              type   : 'empty',
              prompt : 'Seleccione un año'
            }]
          }
        }
      });
    });
  </script>
@stop

@section('contenido')
   <!--Inicio del Modal de confirmacion de regresar a index-->
  <div class="ui small modal" id="regresar">
    <i class="close icon"></i>
    <div class="ui icon header">
      <i class="archive icon"></i>
      Descartar registro
    </div>
    <div class=" content">
        <p>¿Estás seguro que deseas regresar?. Se perderan todos los datos sin guardar.</p>
    </div>
    <div class="actions">
      <div class="ui negative cancel button">
        <i class="remove icon"></i>
        No
      </div>
      <div class="ui positive button" onclick=window.location.href="{{route('ordenes.index')}}">
        <i class="checkmark icon"></i>
        Si
      </div>
    </div>
  </div>
  <!--Final del Modal de confirmacion de regresar a index-->

  <!--Inicio del Modal de confirmacion de envio de formulario-->
  <div class="ui modal" id="guardar">
    <i class="close icon"></i>
    <div class="ui icon header">
      <i class="archive icon"></i>
      Guardar registro nuevo
    </div>
    <div class="content">
        <p>¿Deseas guardar el registro de la localidad?</p>
    </div>
    <div class="actions">
        <div class="ui negative cancel button">
          <i class="remove icon"></i>
          No
        </div>
        <button class="ui positive submit button" type="submit" form="registro_form">
          <i class="checkmark icon"></i>
          Si
        </button>
    </div>
  </div>
  <!--Final del Modal de confirmacion de envio de formulario-->

  <!--Inicio del Contenedor de forma de registro-->
  <div class="ui grid container">
    <div class="row">
      <div class="column">
        <!--Inicio de la forma de registro-->
        <form id="registro_form" class="ui form" action="{{route('ordenes.store')}}" method="POST">
          <input type="hidden" name="_token" value="{{csrf_token()}}">
          <input type="hidden" name="_method" value="POST">
          <h4 class="ui horizontal divider header">
            <i class="tag icon">
            </i>
            Datos generales
          </h4>
          <!-- Inicio de la Seccion de datos generales -->
            <!-- Inicio de la primera fila -->
            <div class="three fields">
              <!-- Input text para el campo de "Nombre" -->
              <div class="seven wide required field">
                <label class="prompt">Número de Folio</label>
                <input type="text" placeholder="Ej. 4563156..." name="no_folio">
              </div>

              <!-- Select para el campo de "Presentacion" -->
              <div class="three wide required field">
                <label class="prompt">Programas Alimenticios</label>
                <select class="ui fluid dropdown" name="programa_id">
                  <option value=""></option>
                  @foreach($programas as $programa)
                  <option value="{{$programa->id_programa}}">{{$programa->tipo}}</option>
                  @endforeach
                </select>
              </div>
            </div>
            <!-- Final de la primera fila -->

            <!-- Inicio de la segunda fila -->
              <div class="two fields">

                 <!-- Input text para el campo de "Municipio" -->
                 <div class="three wide required field">
                    <label class="prompt">Municipio</label>
                    <select class="ui fluid dropdown" name="municipio_id">
                      <option value=""></option>
                      @foreach($municipios as $municipio)
                      <option value="{{$municipio->id}}">{{$municipio->nombre}}</option>
                      @endforeach
                    </select>
                 </div>

                 <!-- Input text para el campo de "Provedor" -->
                 <div class="three wide required field">
                    <label class="prompt">Mes</label>
                    <select class="ui fluid dropdown" name="mes">
                      <option value=""></option>
                      @foreach($meses as $mes)
                      <option value="{{$mes}}">{{$mes}}</option>
                      @endforeach
                    </select>
                 </div>

                 <!-- Select para el campo de "Unidad de Medida" -->
                 <div class="two wide required field">
                   <label class="prompt">Año</label>
                   <select class="ui fluid dropdown" name="anio">
                     <option value=""></option>
                     @foreach($anios as $anio)
                     <option value="{{$anio}}">{{$anio}}</option>
                     @endforeach
                   </select>
                 </div>

              </div>
            <!-- Final de la segunda fila -->
          <!-- Final de la Seccion de datos generales -->
        </form>
        <!--Final de la forma de registro-->
      </div>
    </div>
  </div>
  <!--Final del Contenedor de forma de registro-->
@stop

resources/views/ordenes/index.blade.php
@extends('layouts.master')

@section('botones')
  <!-- Inicio del botón crear -->
  <button class="ui circular massive right floated pink plus icon button" onclick=window.location.href="{{route('ordenes.create')}}">
    <i class="plus icon"></i>
  </button>
  <!-- Fin del botón crear -->
@stop

@section('titulo_seccion')
  Ordenes de Compra
@stop

@section('scripts')

@stop

@section('contenido')

  <!--Inicio de la tabla sin filtrado de eliminados-->
  <table class="ui selectable sortable teal celled table">
    <thead>
      <tr>
        <th class="two wide center aligned">No. Folio</th>
        <th class="six wide center aligned">Programa Alimenticio</th>
        <th class="three wide center aligned">Municipio</th>
        <th class="one wide center aligned">Mes</th>
        <th class="one wide center aligned">Año</th>
        <th class="one wide center aligned">Ver</th>
      </tr>
    </thead>
    <tbody>
      @foreach($ordenes_de_compra as $orden_de_compra)
        <tr>
          <td class="center aligned">{{$orden_de_compra->no_folio}}</td>
          <td class="center aligned">{{$orden_de_compra->programa->tipo}}</td>
          <td class="center aligned">{{$orden_de_compra->municipio->nombre}}</td>
          <td class="center aligned">{{$orden_de_compra->mes}}</td>
          <td class="center aligned">{{$orden_de_compra->anio}}</td>
          <td onclick=window.location.href="{{route('ordenes.show', $orden_de_compra->id)}}" class=" selectable center aligned">
             <i class="info circle big icon "></i>
          </td>
        </tr>
      @endforeach
    </tbody>
    <tfoot>
      <tr>
        <th colspan="9">
          <div class="ui right floated pagination menu">
            <a href="{!! $ordenes_de_compra->previousPageUrl() !!}" class="icon item">
              <i class="left chevron icon "></i>
            </a>
            @for($pages = 1; $pages <= $ordenes_de_compra->lastPage(); $pages++)
                <a href="{!! $ordenes_de_compra->url($pages) !!}" class="item ">{{$pages}}</a>
            @endfor
            <a href="{!! $ordenes_de_compra->nextPageUrl() !!}" class="icon item">
              <i class="right chevron icon "></i>
            </a>
          </div>
        </th>
      </tr>
    </tfoot>
  </table>
  <!--Final de la tabla sin filtrado de eliminados-->

@stop

resources/views/ordenes/show.blade.php
@extends('layouts.master')

@section('botones')

  <div style="visibility:hidden">
    <br />..
  </div>
  <!-- Inicio del botón de eliminar o rehabilitar, siendo el caso -->
  <div class="row">
    <button class="  ui circular massive right floated teal trash outline icon button" onclick="$('#eliminar').modal('show');" >
      <i class="trash outline icon"></i>
    </button>
  </div>
  <!-- Fin del botón de eliminar o rehabilitar, siendo el caso -->

  <div style="visibility:hidden">
    <br />..
  </div>

  <!-- Inicio de botón de regresar al index -->
  <div class="row">
    <button class=" ui circular massive right floated chevron left icon button" onclick=window.location.href="{{route('ordenes.index')}}">
      <i class="chevron left icon"></i>
    </button>
  </div>
  <!-- Fin de botón de regresar al index -->
@stop

@section('titulo_seccion')
  {{$orden_de_compra->programa->tipo}} {{$orden_de_compra->mes}} del {{$orden_de_compra->anio}}
@stop

@section('scripts')
   <script>
      $( document ).ready(function() {
         // Inicialización de elementos de Semantic UI
         $('.ui.modal').modal();
      });
   </script>
@stop

@section('contenido')

   <!-- Inicio del Modal de confirmacion de regreso a index -->
   <div class="ui small modal" id="eliminar">
      <i class="close icon"></i>
      <div class="ui icon header">
         <i class="archive icon"></i>
         Eliminar Orden de Compra
      </div>
      <div class=" content">
         <p>¿Seguro que deseas eliminar la orden de compra?</p>
      </div>
      <div class="actions">
           <div class="ui negative cancel button">
             <i class="remove icon"></i>
             No
           </div>
           <button class="ui positive submit button "  type="submit" form="vista" value="delete">
             <i class="checkmark icon"></i>
             Si
           </button>
      </div>
   </div>
   <!-- Final del Modal de confirmacion de regreso a index -->


   <!--Inicio de forma de visualizacion que utiliza el metodo destroy para eliminar Producto-->
   <form id="vista" class="ui form" action="{{route('ordenes.destroy', $orden_de_compra->id)}}" method="POST" >
      <input type="hidden" name="_token" value="{{csrf_token()}}">
      <input type="hidden" name="_method" value="DELETE">

      <!--Inicio de la tabla sin filtrado de eliminados-->
      <table class="ui selectable sortable teal celled table">
        <thead>
          <tr>
            <th class="two wide center aligned">No.</th>
            <th class="six wide center aligned">Productos</th>
            <th class="three wide center aligned">Marca</th>
            <th class="one wide center aligned">Presentacion</th>
            <th class="one wide center aligned">Contenido Neto</th>
            <th class="one wide center aligned">Unidad de Medida</th>
            <th class="one wide center aligned">Cantidad</th>
            <th class="one wide center aligned">Precio</th>
            <th class="one wide center aligned">Costo Total</th>
          </tr>
        </thead>
        <tbody>
          @foreach($productos as $producto)
            <tr>
              <td class="center aligned">{{($i++)+1}}</td>
              <td class="center aligned">{{$producto->nombre}}</td>
              <td class="center aligned">{{$producto->marca}}</td>
              <td class="center aligned">{{$producto->presentacion->nombre}}</td>
              <td class="center aligned">{{$producto->contenido_neto}}</td>
              <td class="center aligned">{{$producto->unidad_de_medida->nombre}}</td>
              <td class="center aligned">{{$cantidades[$i -1]}}</td>
              <td class="center aligned">{{$producto->precio}}</td>
              <td class="center aligned">{{$precios[$i-1]}}</td>
            </tr>
          @endforeach
        </tbody>
      </table>
      <!--Final de la tabla sin filtrado de eliminados-->

   </form>
   <!--Final de forma de visualizacion que utiliza el metodo destroy para eliminar Producto-->
@stop